### PR TITLE
Update make commands and readme

### PR DESCRIPTION
**Pull request by mforner13**
This PR updates makes the following changes to the commands in the Makefile:

- Separates out the `setup-db` command into `setup-db` and `create-db` - to enable developers to apply migrations and load fixtures when the `defend` database already exists
- Adds the `load-data` command into the `setup-db` command, given that the DIT `gov_department` fixture is necessary for the app to run with staff SSO

It also adds the following details to the Readme:
- How to set the needed environment variables
- To only access the application on localhost:8000

### CODE REVIEW

**Comment by NickFitz** [comment]
In Readme.md line 21: `python manage.py run server` - should be `runserver` (no space, though autocomplete is determined to insert one).

**Review by NickFitz — APPROVED** [review]
👍

**Comment by dev-digital** [comment]
Looks good to me as well :+1: 

I have some comments not directly related to the changes within this PR. like

- There is the requirement for _python runtime 3.8_ for this repo, which has not been captured.

Below are more of a question than comment

- running   _make tests_ touch db container. Not sure the reason behind it. Ideally tests(not integration ones) should run in isolation with all dependencies mocked out

- Any reason for requirements file to be not at root ?

@mforner13  Shall we get the changes merged and create new issues for above if we want to address them ?

**Comment by mforner13** [comment]
> Looks good to me as well 👍
> 
> I have some comments not directly related to the changes within this PR. like
> 
> * There is the requirement for _python runtime 3.8_ for this repo, which has not been captured.
> 
> Below are more of a question than comment
> 
> * running   _make tests_ touch db container. Not sure the reason behind it. Ideally tests(not integration ones) should run in isolation with all dependencies mocked out
> * Any reason for requirements file to be not at root ?
> 
> @mforner13 Shall we get the changes merged and create new issues for above if we want to address them ?

Thanks @dev-digital ! I've added a line about python 3.8 to the readme and also removed the db setup from the `make tests` command. 

For the requirements.txt file not being in the root - we did try to move it out, but had an issue which I now can't remember unfortunately 😞  Adding it to issues sounds like a good plan if you think it's needed!

**Review by dev-digital — APPROVED** [review]
:rocket: 

BTW, I would create an issue (minor) for the location of requirements file (and possibly other re-structuring as we have duplicated directories - _defend_data_capture/defend_data_capture/_ ) which can be picked-up if we run out of things to do :grin:

**Comment by mforner13** [comment]
> 🚀
> 
> BTW, I would create an issue (minor) for the location of requirements file (and possibly other re-structuring as we have duplicated directories - _defend_data_capture/defend_data_capture/_ ) which can be picked-up if we run out of things to do 😁

Created issue [here](https://github.com/uktrade/defend-data-capture/issues/26) 😺

**Pull request merged**
